name: Build Memory Tool

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++
      
    - name: Compile MemoryTool
      run: g++ -std=c++11 -pthread MemoryTool.cpp main.cpp -o MemoryTool
      
    - name: Verify binary
      run: |
        file MemoryTool
        ./MemoryTool || echo "Program executed (may exit normally)"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: MemoryTool-Linux
        path: MemoryTool
